stages:
  - name: pam-duress
    from: docker.io/library/debian:12
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git build-essential libpam0g-dev libssl-dev
          - git clone https://github.com/nuvious/pam-duress.git
          - cd pam-duress && make
          - mkdir -p /out/ && mv ./bin/* /out
modules:
  - type: copy
    from: pam-duress
    src: /out/duress_sign
    dest: /usr/bin/
  - type: copy
    from: pam-duress
    src: /out/pam_test
    dest: /usr/bin/
  - type: copy
    from: pam-duress
    src: /out/pam_duress.so
    dest: /usr/lib64/security
